networks:
    laravel:

services:

    nginx_fcm:
        image: nginx:stable-alpine
        container_name: nginx_fcm
        ports:
            - "80:80"
        volumes:
            - ${PWD}/../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db_fcm
            - app_fcm
        networks:
            - laravel


    db_fcm:
        image: postgres:14.2-alpine
        container_name: db_fcm
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=fcm
            - POSTGRES_USER=fcm_admin
            - POSTGRES_PASSWORD=12qwaszx
        networks:
            - laravel

    app_fcm:
        build:
            context: ./php
        container_name: app_fcm
        volumes:
            - ${PWD}/../:/var/www/html
        ports:
            - "9000:9000"
            - "5173:5173"
        networks:
            - laravel

    composer:
        build:
            context: ./php
        volumes:
            - ${PWD}/../:/var/www/html
        entrypoint: composer
        command:
            - list

    artisan:
        build:
            context: ./php
        volumes:
            - ${PWD}/../:/var/www/html
        entrypoint: php artisan
        command:
            - list
        networks:
            - laravel
